name: tools

services:
  dead-link-checker:
    container_name: dead-link-checker-api
    build:
      context: ./dead-link-checker
      dockerfile: Dockerfile
    image: dead-link-checker:latest
    restart: unless-stopped
    ports:
      - "8765:8000"
    environment:
      DEADLINKS_DATABASE_NAME: ${DEADLINKS_DATABASE_NAME}
      DEADLINKS_DATABASE_USERNAME: ${DEADLINKS_DATABASE_USERNAME}
      DEADLINKS_DATABASE_PASSWORD: ${DEADLINKS_DATABASE_PASSWORD}
      DEADLINKS_DATABASE_HOST: ${DEADLINKS_DATABASE_HOST}
      DEADLINKS_DATABASE_PORT: ${DEADLINKS_DATABASE_PORT}
      DEADLINKS_STRAPI_URL: ${DEADLINKS_STRAPI_URL}
      DEADLINKS_STRAPI_API_KEY: ${DEADLINKS_STRAPI_API_KEY}
      DEADLINKS_FRONTEND_URL: ${DEADLINKS_FRONTEND_URL}
      DEADLINKS_BASIC_AUTH_USERNAME: ${DEADLINKS_BASIC_AUTH_USERNAME}
      DEADLINKS_BASIC_AUTH_PASSWORD: ${DEADLINKS_BASIC_AUTH_PASSWORD}
      DEADLINKS_PRODUCT_URL_PATTERNS: ${DEADLINKS_PRODUCT_URL_PATTERNS}
      DEADLINKS_PROTECTED_FRONTEND_HOSTS: ${DEADLINKS_PROTECTED_FRONTEND_HOSTS}
